/**
 * Premium Sections Builder
 * 
 * Generates rich, visually complete landing page sections from AI plan data.
 * Each section is populated with contextual content derived from the business
 * description, name, and SEO data provided during site creation.
 */

import type { LandingPageSection } from '@/domain/entities'
import type {
    HeroContent,
    FeaturesContent,
    BenefitsGridContent,
    ProcessStepsContent,
    StatsContent,
    TestimonialsContent,
    FaqContent,
    CtaBannerContent,
    ContactFormContent,
} from '@/domain/entities/landing-page-sections'

interface PlanContext {
    siteName: string
    seoTitle?: string
    seoDescription?: string
    keywords?: string[]
    pages?: string[]
    premiumDesign?: string
    /** AI-generated section content if available */
    aiSections?: AISectionContent
}

/** Rich section content generated by the AI during plan creation */
export interface AISectionContent {
    heroKicker?: string
    heroHeadline?: string
    heroSubheadline?: string
    heroCta?: string
    heroTrustBadges?: string[]
    heroImagePrompt?: string
    features?: Array<{ icon: string; title: string; description: string }>
    benefits?: Array<{ title: string; description: string }>
    processSteps?: Array<{ title: string; description: string }>
    stats?: Array<{ value: string; label: string }>
    testimonials?: Array<{ name: string; role: string; company: string; quote: string; rating: number }>
    faqItems?: Array<{ question: string; answer: string }>
    ctaTitle?: string
    ctaSubtitle?: string
    galleryImagePrompts?: string[]
}

const FEATURE_ICONS = ['Zap', 'Shield', 'TrendingUp', 'Target', 'Layers', 'BarChart3']

export function buildPremiumSections(ctx: PlanContext): LandingPageSection[] {
    const ai = ctx.aiSections
    const sections: LandingPageSection[] = []
    let order = 0

    // ─── 1. Hero ───────────────────────────────────────────────────────
    const heroContent: HeroContent = {
        kicker: ai?.heroKicker || 'Bem-vindo ao futuro do seu negócio',
        headline: ai?.heroHeadline || ctx.siteName,
        subheadline: ai?.heroSubheadline || ctx.seoDescription || `Conheça ${ctx.siteName} — soluções profissionais para transformar seus resultados.`,
        ctaText: ai?.heroCta || 'Quero saber mais',
        ctaUrl: '#contato',
        backgroundImageUrl: null,
        heroImageUrl: null,
        layout: 'split',
        trustBadges: ai?.heroTrustBadges || ['Sem compromisso', 'Atendimento personalizado', 'Resultados comprovados'],
        alignment: 'left',
    }
    sections.push({
        id: 'hero-0',
        type: 'hero',
        order: order++,
        visible: true,
        content: heroContent,
    } as LandingPageSection)

    // ─── 2. Stats ──────────────────────────────────────────────────────
    const statsContent: StatsContent = {
        title: 'Nossos Números',
        items: ai?.stats || [
            { value: '500+', label: 'Clientes atendidos' },
            { value: '98%', label: 'Satisfação' },
            { value: '24/7', label: 'Suporte disponível' },
            { value: '3x', label: 'Mais eficiência' },
        ],
    }
    sections.push({
        id: 'stats-1',
        type: 'stats',
        order: order++,
        visible: true,
        content: statsContent,
    } as LandingPageSection)

    // ─── 3. Features ───────────────────────────────────────────────────
    const featuresContent: FeaturesContent = {
        title: 'Por que escolher a gente?',
        subtitle: 'Recursos pensados para o seu sucesso',
        columns: 3,
        items: ai?.features || [
            { icon: 'Zap', title: 'Velocidade', description: 'Processos ágeis e resultados em tempo real para acompanhar o ritmo do seu negócio.' },
            { icon: 'Shield', title: 'Segurança', description: 'Proteção de dados avançada e conformidade com as melhores práticas do mercado.' },
            { icon: 'TrendingUp', title: 'Crescimento', description: 'Estratégias orientadas por dados para escalar suas operações com inteligência.' },
            { icon: 'Target', title: 'Precisão', description: 'Segmentação cirúrgica e personalização que converte visitantes em clientes.' },
            { icon: 'Layers', title: 'Integração', description: 'Conecte-se com suas ferramentas favoritas sem atrito e sem retrabalho.' },
            { icon: 'BarChart3', title: 'Análise', description: 'Dashboards intuitivos com métricas que realmente importam para o seu negócio.' },
        ],
    }
    sections.push({
        id: 'features-2',
        type: 'features',
        order: order++,
        visible: true,
        content: featuresContent,
    } as LandingPageSection)

    // ─── 4. Benefits Grid ──────────────────────────────────────────────
    const benefitsContent: BenefitsGridContent = {
        title: 'Resultados que você vai sentir na prática',
        subtitle: 'Mais do que funcionalidades — ganhos reais para o seu dia a dia.',
        items: ai?.benefits || [
            { title: 'Mais produtividade', description: 'Automatize tarefas repetitivas e libere sua equipe para focar no que importa.' },
            { title: 'Mais previsibilidade', description: 'Tenha clareza de cada etapa com dados organizados e acompanhamento em tempo real.' },
            { title: 'Mais conversão', description: 'Melhore a experiência do cliente final e aumente suas oportunidades de fechamento.' },
            { title: 'Menos custos operacionais', description: 'Reduza retrabalho e erros com processos padronizados e automatizados.' },
        ],
    }
    sections.push({
        id: 'benefits-3',
        type: 'benefits_grid',
        order: order++,
        visible: true,
        content: benefitsContent,
    } as LandingPageSection)

    // ─── 5. Process Steps ──────────────────────────────────────────────
    const processContent: ProcessStepsContent = {
        title: 'Como funciona',
        subtitle: 'Implementação simples, guiada e orientada para resultado.',
        steps: ai?.processSteps || [
            { title: 'Diagnóstico inicial', description: 'Entendemos seu cenário atual, seus objetivos e os pontos críticos do seu negócio.' },
            { title: 'Estratégia personalizada', description: 'Criamos um plano de ação sob medida, alinhado às suas metas e ao seu orçamento.' },
            { title: 'Implementação ágil', description: 'Configuramos e ativamos tudo com velocidade, sem interromper sua operação.' },
            { title: 'Otimização contínua', description: 'Monitoramos métricas e evoluímos a estratégia com base em dados reais.' },
        ],
    }
    sections.push({
        id: 'process-4',
        type: 'process_steps',
        order: order++,
        visible: true,
        content: processContent,
    } as LandingPageSection)

    // ─── 6. Testimonials ───────────────────────────────────────────────
    const testimonialsContent: TestimonialsContent = {
        title: 'O que nossos clientes dizem',
        items: ai?.testimonials
            ? ai.testimonials.map(t => ({ ...t, avatarUrl: null }))
            : [
                { name: 'Ana Costa', role: 'Diretora de Marketing', company: 'TechBrasil', avatarUrl: null, quote: 'Transformou completamente a forma como nos comunicamos com nossos clientes. Os resultados apareceram já no primeiro mês.', rating: 5 },
                { name: 'Rafael Mendes', role: 'CEO', company: 'Inovatech', avatarUrl: null, quote: 'Atendimento excepcional e plataforma robusta. Recomendo para qualquer empresa que queira escalar suas operações.', rating: 5 },
                { name: 'Juliana Santos', role: 'Head de Vendas', company: 'Conecta Digital', avatarUrl: null, quote: 'A melhor decisão que tomamos foi adotar esta solução. ROI positivo em menos de 60 dias.', rating: 5 },
            ],
    }
    sections.push({
        id: 'testimonials-5',
        type: 'testimonials',
        order: order++,
        visible: true,
        content: testimonialsContent,
    } as LandingPageSection)

    // ─── 7. FAQ ────────────────────────────────────────────────────────
    const faqContent: FaqContent = {
        title: 'Perguntas Frequentes',
        subtitle: 'Tire suas dúvidas antes de começar.',
        items: ai?.faqItems || [
            { question: 'Como funciona o processo de implantação?', answer: 'Nosso time guia você em cada etapa — do diagnóstico inicial à ativação completa. O processo geralmente leva de 3 a 7 dias úteis.' },
            { question: 'Preciso de conhecimento técnico para usar?', answer: 'Não. A plataforma foi desenhada para ser intuitiva e acessível, com interface amigável e suporte dedicado para tirar qualquer dúvida.' },
            { question: 'Existe algum período de teste?', answer: 'Sim! Oferecemos um período de experimentação gratuito para que você possa conhecer todas as funcionalidades antes de decidir.' },
            { question: 'Posso cancelar a qualquer momento?', answer: 'Com certeza. Não há contratos de fidelidade. Você pode cancelar quando quiser, sem burocracia ou multas.' },
            { question: 'Vocês oferecem suporte em português?', answer: 'Sim, todo o nosso suporte é em português, com atendimento humanizado via chat, e-mail e WhatsApp.' },
        ],
    }
    sections.push({
        id: 'faq-6',
        type: 'faq',
        order: order++,
        visible: true,
        content: faqContent,
    } as LandingPageSection)

    // ─── 8. CTA Banner ─────────────────────────────────────────────────
    const ctaBannerContent: CtaBannerContent = {
        title: ai?.ctaTitle || 'Pronto para transformar seus resultados?',
        subtitle: ai?.ctaSubtitle || 'Comece agora mesmo — sem compromisso e sem cartão de crédito.',
        ctaText: 'Falar com um especialista',
        ctaUrl: '#contato',
    }
    sections.push({
        id: 'cta-7',
        type: 'cta_banner',
        order: order++,
        visible: true,
        content: ctaBannerContent,
    } as LandingPageSection)

    // ─── 9. Contact Form ───────────────────────────────────────────────
    const contactContent: ContactFormContent = {
        title: 'Entre em contato',
        subtitle: 'Preencha o formulário abaixo e nossa equipe entrará em contato em até 24 horas.',
        fields: ['name', 'email', 'phone', 'company', 'message'],
        submitText: 'Enviar mensagem',
        successMessage: 'Mensagem enviada com sucesso! Entraremos em contato em breve.',
    }
    sections.push({
        id: 'contact-8',
        type: 'contact_form',
        order: order++,
        visible: true,
        content: contactContent,
    } as LandingPageSection)

    return sections
}
