export type { IContactRepository, CreateContactInput } from './contact-repository'
export type { IDealRepository, CreateDealInput } from './deal-repository'
export type { IMessageRepository, CreateMessageInput, RawMessageWithContact } from './message-repository'
export type { ICampaignRepository, CreateCampaignInput, UpdateCampaignInput, CampaignRow } from './campaign-repository'
export type { IAutomationRepository, AutomationRow, AutomationStep, AutomationWorkflow, CreateAutomationInput, UpdateAutomationInput } from './automation-repository'
export type { IUserRepository, UserProfile } from './user-repository'
export type { IWhatsAppService, SendWhatsAppInput, SendWhatsAppResult } from './whatsapp-service'
export type { IEmailService, SendEmailInput, SendBatchEmailInput, SendEmailResult } from './email-service'
export type { ILandingPageRepository, CreateLandingPageInput, UpdateLandingPageInput } from './landing-page-repository'
export type { IKnowledgeBaseRepository, CreateKnowledgeBaseInput, KnowledgeBaseMatch } from './knowledge-base-repository'
export type { IChatSessionRepository, CreateChatSessionInput, CreateChatMessageInput } from './chat-session-repository'
export type { IAnalyticsRepository, TrackEventInput, PageAnalyticsSummary } from './analytics-repository'
