export { SupabaseContactRepository } from './contact-repository'
export { SupabaseDealRepository } from './deal-repository'
export { SupabaseMessageRepository } from './message-repository'
export { SupabaseCampaignRepository, SupabaseAutomationRepository } from './campaign-repository'
export { SupabaseUserRepository } from './user-repository'
export { SupabaseLandingPageRepository } from './landing-page-repository'
export { SupabaseKnowledgeBaseRepository } from './knowledge-base-repository'
export { SupabaseChatSessionRepository } from './chat-session-repository'
export { SupabaseAnalyticsRepository } from './analytics-repository'
