export { SupabaseContactRepository } from './contact-repository'
export { SupabaseDealRepository } from './deal-repository'
export { SupabaseMessageRepository } from './message-repository'
export { SupabaseCampaignRepository } from './campaign-repository'
export { SupabaseAutomationRepository } from './automation-repository'
export { SupabaseUserRepository } from './user-repository'
export { SupabaseLandingPageRepository } from './landing-page-repository'
export { SupabaseKnowledgeBaseRepository } from './knowledge-base-repository'
export { SupabaseChatSessionRepository } from './chat-session-repository'
export { SupabaseAnalyticsRepository } from './analytics-repository'
export { SupabaseInstagramContentRepository, SupabaseInstagramAccountRepository, SupabaseInstagramAutoConfigRepository } from './instagram-repository'
export { SupabaseProductRepository } from './product-repository'
